---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    -- add more things to the ensure_installed table protecting against community packs modifying it
    opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, {
      "cmake",
      "comment",
      "cmake",
      "cpp",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "hcl",
      "hjson",
      "html",
      "ini",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "kotlin",
      "lua",
      "luadoc",
      "ninja",
      "passwd",
      "pem",
      "php",
      "prisma",
      "python",
      "regex",
      "requirements",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "svelte",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",

    })
  end,
}
